### ISSUE TITLE
Can't able to use same component multiple times in a network

### ISSUE THREAD

**Issue by kshivam213** [jpaulm/javafbp#12]
I have 4 components called (A, B, C, D), using these I am creating network my network is like this 
A -> B -> C -> B.  It executed this A-> B-> C but when C is trying to send a packet to B it is throwing this error -----  Could not deliver the packet to C -OUT.  Can't we use the same component multiple times in a network?

**Comment by jpaulm** [comment]
Hi Shivam,

Don’t see why this should be a problem.  Remember that the two B’s have to
be separate processes- with unique names.  They can of course use the same
component  names.  For historical reasons we use ‘component ‘ in the
network definition.  Sorry!  I know it’s confusing!

HTH

**Comment by kshivam213** [comment]
Hi Paul,
Thanks for your response, yes I was giving the same component name to both B's. I changed the name now both B's are separate processes and its working. 

Regards,
Shivam

**Comment by jpaulm** [comment]
Just to clarify: multiple processes *can* use the same component - I assume
that is what you meant...

Regards

**Comment by jpaulm** [comment]
Unless you meant the same process- in which case you have a loop network-
so see the chapter in my book on loops!

**Comment by kshivam213** [comment]
Yes, I meant for the same component having multiple processes. I was not creating multiple processes and using the same process so it threw me couldn't deliver the packet error.

**Comment by jpaulm** [comment]
Thanks, Shivam!  Interesting that you say " the same component having
multiple processes" - I tend to think of multiple processes using the same
component!  For me, components are passive, while processes are active, so
components can't "have"... they "are had"!

Regards,

Paul M.
