### ISSUE TITLE
On The "Save File" dialog pressing escape or closing the window should cancel, not exit without save.

### ISSUE THREAD

**Issue by gedb** [jpaulm/javafbp#16]
I'm using drawfbp-2.18.4 on Windows 10 and I find my self repeatedly losing my work because of pressing escape to many times.

If I load a diagram, make a change and then press escape I get the save changes dialog.

It has 3 options: Yes (the default), No and Cancel.

I can also dismiss the dialog by pressing escape or clicking the windows close 'x' button in the top right hand corner.

If I press the 'x' or press escape then it has the same effect as choosing 'No'.  DrawFBP closes without saving my changes.

Personally I would expect it to have the same effect as choosing 'Cancel'.  The dialog should close and return me to the main screen.

**Comment by jpaulm** [comment]
Absolutely right!  Well spotted!  Should have this fixed soon!  There seems to be a slight problem when you have two modified diagrams open at the same time...  Will try to get that fixed too!

Thanks!

**Comment by jpaulm** [comment]
Hi @gedb , I think I have it fixed!  I have put a new load module up on all the usual places... but with the same version no.  Hope this doesn't call confusion!  I felt bad, as it must be frustrating to lose work into which you have put time and creativity...  Apologies!  Hope this latest version is better!

I really liked your suggestions about a graphic diff - if nobody has stepped up to it, and winter looks like it is going to be too quiet, I might give it a try myself!  

Hope you had a good summer!

Best regards,

Paul

cc @bobcorrick

**Comment by jpaulm** [comment]
Fixed! Sorry about that!
