### ISSUE TITLE
Question : Skipping computation if inputs have not change, how to check that situation ?

### ISSUE THREAD

**Issue by nyue** [jpaulm/javafbp#33]
I am exploring FBP.

I just received the 2nd Edition of the book from Amazon.

I have been looking at both the Java and C++ code

One of the conceptual question I have is with regards to the input ports.

How does one check if the input ports data have not change since the last
time it was read? For compute intensive tasks, it would be useful not to
reperform the operation if the inputs have not change.

e.g. in JavaFBP, looking at https://jpaulm.github.io/fbp/jsyntax.htm#samplecomp

I see

```
  @Override
  protected void execute() {
    Packet ctp = count.receive();
    if (ctp == null) {
      return;
    }
```

am I correct to understand that checking ctp for null serves such a purpose

turning to cppFBP (http://www.jpaulmorrison.com/fbp/CppFBP.shtml#samplecomp),
I see the _anchor type.

What would be the recommended way to check if the inputs have not change and skip the computation ?

**Comment by jpaulm** [comment]
@nyue Thanks for your question!  It's great that someone is digging into the code!  However, I think there is a bit of a misunderstanding here, and maybe I am so close to FBP that I didn't explain it clearly!

An FBP process is like a machine being fed one object at a time (perhaps several objects on multiple input ports), so a process does a `receive` from a given input port and then waits until an object arrives at that port (or it realizes that no more objects will be arriving).  The port is not a *value* that changes from time to time; it sees a series of "things" which it will receive.   So, a return value of null from `receive` means only that there are no more "things" to receive - this is the only meaning of the null value.  When the process does a `return` *after* all input ports have received null, the process closes down.

Hope this helps, and best regards.

Paul M.
