### ISSUE TITLE
Publish on Maven Central

### ISSUE THREAD

**Issue by jonnor** [jpaulm/javafbp#5]
I cannot find JavaFBP on Maven Central, the primary repository for Java libraries.
This makes it tricky to use JavaFBP as a dependency of another project

**Comment by jpaulm** [comment]
Hi @jonnor, I can't understand how this remained unclosed for almost 2 years!  My test case works - so what is the status of this issue?  Do JavaFBP and/or javafbp-websockets need to be added to Maven?  Also, I think you said you got java-websockets 1.3.0 from Maven - I don't remember adding it, and it doesn't seem to be there now!  Help would be appreciated!
